# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:28
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0002_auto_20161223_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='performance',
            field=tinymce.models.HTMLField(),
        ),
    ]
