# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0003_auto_20170211_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
