# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0004_auto_20161223_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(upload_to='avatar'),
        ),
    ]
