# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0005_auto_20161223_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(default='photo', upload_to='profile'),
            preserve_default=False,
        ),
    ]
