# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0006_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='job',
            field=models.CharField(default='jobs', max_length=100),
            preserve_default=False,
        ),
    ]
