# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0010_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Date_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='available',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techmentorapp.Date_Time'),
        ),
        migrations.AddField(
            model_name='available',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techmentorapp.Mentor'),
        ),
    ]
