# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0011_auto_20161228_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Date_Time',
        ),
    ]
