# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 16:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0015_infomation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomation',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
