# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0016_auto_20170118_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='job',
            field=models.CharField(default='エンジニア', max_length=100),
        ),
    ]
