# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0017_auto_20170208_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, upload_to='profile'),
        ),
    ]
