# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0020_auto_20170209_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
