# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('techmentorapp', '0021_auto_20170209_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
